//! # vld-utoipa — Bridge between `vld` and `utoipa`
//!
//! This crate lets you use `vld` validation schemas as the **single source of truth**
//! for both runtime validation and OpenAPI documentation generated by
//! [utoipa](https://docs.rs/utoipa).
//!
//! Instead of duplicating schema definitions with `#[derive(ToSchema)]` **and**
//! `vld::schema!`, you define validation rules once in `vld` and get `utoipa`
//! compatibility for free.
//!
//! # Quick Start
//!
//! ```rust
//! use vld::prelude::*;
//! use vld_utoipa::impl_to_schema;
//!
//! // 1. Define your validated struct as usual
//! vld::schema! {
//!     #[derive(Debug)]
//!     pub struct User {
//!         pub name: String => vld::string().min(2).max(50),
//!         pub email: String => vld::string().email(),
//!     }
//! }
//!
//! // 2. Bridge to utoipa — one line
//! impl_to_schema!(User);
//!
//! // Now `User` implements `utoipa::ToSchema` and can be used in
//! // `#[utoipa::path]` annotations.
//! ```
//!
//! # Converting arbitrary JSON Schema
//!
//! ```rust
//! use vld_utoipa::json_schema_to_schema;
//!
//! let json_schema = serde_json::json!({
//!     "type": "object",
//!     "required": ["name"],
//!     "properties": {
//!         "name": { "type": "string", "minLength": 1 }
//!     }
//! });
//!
//! let utoipa_schema = json_schema_to_schema(&json_schema);
//! // Returns `utoipa::openapi::RefOr<utoipa::openapi::schema::Schema>`
//! ```

use serde_json::Value;
use utoipa::openapi::path::{Parameter, ParameterBuilder, ParameterIn};
use utoipa::openapi::schema::{
    AllOf, Array, Object, OneOf, Schema, SchemaFormat, SchemaType, Type,
};
use utoipa::openapi::{Ref, RefOr, Required};

/// Convert a `serde_json::Value` (JSON Schema) produced by `vld` into a
/// `utoipa::openapi::RefOr<Schema>`.
///
/// This is the core conversion function. It handles:
/// - Primitive types: `string`, `number`, `integer`, `boolean`, `null`
/// - Objects with `properties` and `required`
/// - Arrays with `items`
/// - `oneOf`, `allOf` composites
/// - `enum` values
/// - Numeric constraints: `minimum`, `maximum`, `exclusiveMinimum`, `exclusiveMaximum`, `multipleOf`
/// - String constraints: `minLength`, `maxLength`, `pattern`
/// - Array constraints: `minItems`, `maxItems`
/// - `format`, `description`, `default`, `example`
/// - `$ref` references
///
/// # Example
///
/// ```rust
/// use vld_utoipa::json_schema_to_schema;
///
/// let schema = json_schema_to_schema(&serde_json::json!({"type": "string", "format": "email"}));
/// ```
pub fn json_schema_to_schema(value: &Value) -> RefOr<Schema> {
    match value {
        Value::Object(map) => {
            // Handle $ref
            if let Some(Value::String(ref_path)) = map.get("$ref") {
                return RefOr::Ref(Ref::new(ref_path.clone()));
            }

            // Handle oneOf
            if let Some(Value::Array(items)) = map.get("oneOf") {
                let schemas: Vec<RefOr<Schema>> = items.iter().map(json_schema_to_schema).collect();
                let mut one_of = OneOf::new();
                one_of.items = schemas;
                return RefOr::T(Schema::OneOf(one_of));
            }

            // Handle allOf
            if let Some(Value::Array(items)) = map.get("allOf") {
                let schemas: Vec<RefOr<Schema>> = items.iter().map(json_schema_to_schema).collect();
                let mut all_of = AllOf::new();
                all_of.items = schemas;
                return RefOr::T(Schema::AllOf(all_of));
            }

            // Determine type
            let type_str = map.get("type").and_then(|v| v.as_str()).unwrap_or("object");

            match type_str {
                "array" => {
                    let items_schema = map
                        .get("items")
                        .map(json_schema_to_schema)
                        .unwrap_or_else(|| RefOr::T(Schema::Object(Object::default())));

                    let mut arr = Array::new(items_schema);

                    if let Some(n) = map.get("minItems").and_then(|v| v.as_u64()) {
                        arr.min_items = Some(n as usize);
                    }
                    if let Some(n) = map.get("maxItems").and_then(|v| v.as_u64()) {
                        arr.max_items = Some(n as usize);
                    }

                    RefOr::T(Schema::Array(arr))
                }
                "object" => convert_object(map),
                _ => convert_primitive(map, type_str),
            }
        }
        // Bare true/false schema
        Value::Bool(true) => RefOr::T(Schema::Object(Object::new())),
        _ => RefOr::T(Schema::Object(Object::default())),
    }
}

fn convert_object(map: &serde_json::Map<String, Value>) -> RefOr<Schema> {
    let mut obj = Object::with_type(SchemaType::Type(Type::Object));

    // Properties
    if let Some(Value::Object(props)) = map.get("properties") {
        for (key, val) in props {
            obj.properties
                .insert(key.clone(), json_schema_to_schema(val));
        }
    }

    // Required
    if let Some(Value::Array(req)) = map.get("required") {
        obj.required = req
            .iter()
            .filter_map(|v| v.as_str().map(String::from))
            .collect();
    }

    // Description
    if let Some(Value::String(desc)) = map.get("description") {
        obj.description = Some(desc.clone());
    }

    // Title
    if let Some(Value::String(title)) = map.get("title") {
        obj.title = Some(title.clone());
    }

    // Default
    if let Some(default) = map.get("default") {
        obj.default = Some(default.clone());
    }

    // Example
    if let Some(example) = map.get("example") {
        obj.example = Some(example.clone());
    }

    RefOr::T(Schema::Object(obj))
}

fn to_number(n: f64) -> utoipa::Number {
    if n.fract() == 0.0 {
        utoipa::Number::Int(n as isize)
    } else {
        utoipa::Number::Float(n)
    }
}

fn convert_primitive(map: &serde_json::Map<String, Value>, type_str: &str) -> RefOr<Schema> {
    let schema_type = match type_str {
        "string" => SchemaType::Type(Type::String),
        "number" => SchemaType::Type(Type::Number),
        "integer" => SchemaType::Type(Type::Integer),
        "boolean" => SchemaType::Type(Type::Boolean),
        "null" => SchemaType::Type(Type::Null),
        _ => SchemaType::Type(Type::Object),
    };

    let mut obj = Object::with_type(schema_type);

    // Format
    if let Some(Value::String(fmt)) = map.get("format") {
        obj.format = Some(SchemaFormat::Custom(fmt.clone()));
    }

    // Description
    if let Some(Value::String(desc)) = map.get("description") {
        obj.description = Some(desc.clone());
    }

    // Title
    if let Some(Value::String(title)) = map.get("title") {
        obj.title = Some(title.clone());
    }

    // Default
    if let Some(default) = map.get("default") {
        obj.default = Some(default.clone());
    }

    // Example
    if let Some(example) = map.get("example") {
        obj.example = Some(example.clone());
    }

    // Enum values
    if let Some(Value::Array(vals)) = map.get("enum") {
        obj.enum_values = Some(vals.clone());
    }

    // Pattern (string)
    if let Some(Value::String(pat)) = map.get("pattern") {
        obj.pattern = Some(pat.clone());
    }

    // String constraints
    if let Some(n) = map.get("minLength").and_then(|v| v.as_u64()) {
        obj.min_length = Some(n as usize);
    }
    if let Some(n) = map.get("maxLength").and_then(|v| v.as_u64()) {
        obj.max_length = Some(n as usize);
    }

    // Numeric constraints
    if let Some(n) = map.get("minimum").and_then(|v| v.as_f64()) {
        obj.minimum = Some(to_number(n));
    }
    if let Some(n) = map.get("maximum").and_then(|v| v.as_f64()) {
        obj.maximum = Some(to_number(n));
    }
    if let Some(n) = map.get("exclusiveMinimum").and_then(|v| v.as_f64()) {
        obj.exclusive_minimum = Some(to_number(n));
    }
    if let Some(n) = map.get("exclusiveMaximum").and_then(|v| v.as_f64()) {
        obj.exclusive_maximum = Some(to_number(n));
    }
    if let Some(n) = map.get("multipleOf").and_then(|v| v.as_f64()) {
        obj.multiple_of = Some(to_number(n));
    }

    RefOr::T(Schema::Object(obj))
}

/// Returns `true` when `schema` is a `oneOf` that includes `{ "type": "null" }`.
fn is_nullable_one_of(schema: &Value) -> bool {
    schema
        .get("oneOf")
        .and_then(Value::as_array)
        .is_some_and(|items| {
            items
                .iter()
                .any(|item| item.get("type").and_then(Value::as_str) == Some("null"))
        })
}

/// If `schema` is an optional/nullable `oneOf`, return the non-null branch.
fn unwrap_nullable_schema(schema: &Value) -> &Value {
    if let Some(items) = schema.get("oneOf").and_then(Value::as_array) {
        if let Some(inner) = items
            .iter()
            .find(|item| item.get("type").and_then(Value::as_str) != Some("null"))
        {
            return inner;
        }
    }
    schema
}

/// Convert a vld object `json_schema()` into OpenAPI path/query parameters.
///
/// Each property becomes a [`Parameter`] with per-field validation constraints
/// preserved from the vld schema (e.g. `minLength`, `minimum`).
pub fn json_schema_to_params(value: &Value, parameter_in: ParameterIn) -> Vec<Parameter> {
    let Some(map) = value.as_object() else {
        return Vec::new();
    };

    let properties = map
        .get("properties")
        .and_then(Value::as_object)
        .cloned()
        .unwrap_or_default();

    let required_fields: Vec<&str> = map
        .get("required")
        .and_then(Value::as_array)
        .map(|arr| arr.iter().filter_map(|v| v.as_str()).collect())
        .unwrap_or_default();

    properties
        .into_iter()
        .map(|(name, field_schema)| {
            let nullable = is_nullable_one_of(&field_schema);
            let schema_value = unwrap_nullable_schema(&field_schema);
            let required = if nullable {
                Required::False
            } else if required_fields.contains(&name.as_str()) {
                Required::True
            } else {
                Required::False
            };

            let description = schema_value
                .get("description")
                .and_then(Value::as_str)
                .map(str::to_owned);

            ParameterBuilder::new()
                .name(name)
                .parameter_in(parameter_in.clone())
                .required(required)
                .description(description)
                .schema(Some(json_schema_to_schema(schema_value)))
                .build()
        })
        .collect()
}

/// Map a parameter location hint from [`vld::json_schema::OpenApiParameterIn`] to utoipa.
pub fn parameter_in_from_str(s: &str) -> Option<ParameterIn> {
    match s {
        "query" => Some(ParameterIn::Query),
        "path" => Some(ParameterIn::Path),
        "header" => Some(ParameterIn::Header),
        "cookie" => Some(ParameterIn::Cookie),
        _ => None,
    }
}

#[doc(hidden)]
pub fn resolve_parameter_in_with_override<T: vld::json_schema::OpenApiParameterIn>(
    parameter_in_provider: impl FnOnce() -> Option<ParameterIn>,
    override_hint: Option<ParameterIn>,
) -> Option<ParameterIn> {
    parameter_in_provider()
        .or(override_hint)
        .or_else(|| T::parameter_in().and_then(parameter_in_from_str))
}

#[doc(hidden)]
pub fn resolve_parameter_in<T: vld::json_schema::OpenApiParameterIn>(
    parameter_in_provider: impl FnOnce() -> Option<ParameterIn>,
) -> Option<ParameterIn> {
    resolve_parameter_in_with_override::<T>(parameter_in_provider, None)
}

#[doc(hidden)]
#[macro_export]
macro_rules! __impl_to_schema {
    ($ty:ty, name: None, param_in: None) => {
        $crate::__impl_to_schema_body! {
            $ty,
            name: { },
            param_in: { None::<$crate::utoipa::openapi::path::ParameterIn> },
        }
    };
    ($ty:ty, name: Some($name:expr), param_in: None) => {
        $crate::__impl_to_schema_body! {
            $ty,
            name: { fn name() -> ::std::borrow::Cow<'static, str> {
                ::std::borrow::Cow::Borrowed($name)
            } },
            param_in: { None::<$crate::utoipa::openapi::path::ParameterIn> },
        }
    };
    ($ty:ty, name: None, param_in: Some($param_in:expr)) => {
        $crate::__impl_to_schema_body! {
            $ty,
            name: { },
            param_in: { Some($param_in) },
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __impl_to_schema_body {
    (
        $ty:ty,
        name: { $($name_method:tt)* },
        param_in: { $param_in_override:expr },
    ) => {
        impl $crate::utoipa::PartialSchema for $ty {
            fn schema() -> $crate::utoipa::openapi::RefOr<$crate::utoipa::openapi::schema::Schema> {
                $crate::json_schema_to_schema(&<$ty>::json_schema())
            }
        }

        impl $crate::utoipa::ToSchema for $ty {
            $($name_method)*

            fn schemas(
                schemas: &mut ::std::vec::Vec<(
                    ::std::string::String,
                    $crate::utoipa::openapi::RefOr<$crate::utoipa::openapi::schema::Schema>,
                )>,
            ) {
                #[allow(unused_imports)]
                use $crate::__VldNestedSchemasFallback as _;
                for (name, schema_fn) in <$ty>::__vld_nested_schemas() {
                    let json = schema_fn();
                    schemas.push((name.to_string(), $crate::json_schema_to_schema(&json)));
                }
            }
        }

        impl $crate::utoipa::IntoParams for $ty {
            fn into_params(
                parameter_in_provider: impl Fn() -> Option<$crate::utoipa::openapi::path::ParameterIn>,
            ) -> ::std::vec::Vec<$crate::utoipa::openapi::path::Parameter> {
                let Some(parameter_in) = $crate::resolve_parameter_in_with_override::<$ty>(
                    parameter_in_provider,
                    $param_in_override,
                ) else {
                    return ::std::vec::Vec::new();
                };
                $crate::json_schema_to_params(&<$ty>::json_schema(), parameter_in)
            }
        }
    };
}

/// Bridge a vld type to utoipa (`ToSchema` + `IntoParams` when applicable).
///
/// Works for **request/response bodies** and for **query/path parameters** — the same
/// one-liner as with `#[derive(Validate)]`. Mark parameter structs with utoipa's
/// `#[into_params(parameter_in = Query)]` (or `Path`, `Header`, `Cookie`) on the struct.
///
/// # Body
///
/// ```rust
/// use vld::prelude::*;
/// use vld_utoipa::impl_to_schema;
///
/// vld::schema! {
///     #[derive(Debug)]
///     pub struct CreateUser {
///         pub name: String => vld::string().min(2).max(100),
///         pub email: String => vld::string().email(),
///     }
/// }
///
/// impl_to_schema!(CreateUser);
/// // #[utoipa::path(post, path = "/users", request_body = CreateUser)]
/// ```
///
/// # Query / path parameters
///
/// ```rust
/// use vld::prelude::*;
/// use vld_utoipa::impl_to_schema;
///
/// vld::schema! {
///     #[derive(Debug)]
///     #[into_params(parameter_in = Query)]
///     pub struct SearchQuery {
///         pub q: String => vld::string().min(1).max(200),
///     }
/// }
///
/// impl_to_schema!(SearchQuery);
/// // #[utoipa::path(get, path = "/search", params(SearchQuery))]
/// ```
///
/// Custom OpenAPI component name:
///
/// ```rust
/// # use vld::prelude::*;
/// # use vld_utoipa::impl_to_schema;
/// # vld::schema! {
/// #     #[derive(Debug)]
/// #     pub struct Req { pub x: String => vld::string() }
/// # }
/// impl_to_schema!(Req, "CreateUserRequest");
/// ```
#[macro_export]
macro_rules! impl_to_schema {
    ($ty:ty) => {
        $crate::__impl_to_schema!($ty, name: None, param_in: None);
    };
    ($ty:ty, $name:literal) => {
        $crate::__impl_to_schema!($ty, name: Some($name), param_in: None);
    };
    ($ty:ty, query) => {
        $crate::__impl_to_schema_legacy_suffix_query!($ty);
    };
    ($ty:ty, path) => {
        $crate::__impl_to_schema_legacy_suffix_path!($ty);
    };
    ($ty:ty, header) => {
        $crate::__impl_to_schema_legacy_suffix_header!($ty);
    };
    ($ty:ty, cookie) => {
        $crate::__impl_to_schema_legacy_suffix_cookie!($ty);
    };
}

/// Deprecated alias for [`impl_to_schema!`].
#[macro_export]
#[deprecated(note = "use #[into_params(parameter_in = ...)] on the struct and impl_to_schema!(T)")]
macro_rules! impl_into_params {
    ($ty:ty) => {
        $crate::impl_to_schema!($ty);
    };
    ($ty:ty, $name:literal) => {
        $crate::impl_to_schema!($ty, $name);
    };
    ($ty:ty, Query) => {
        $crate::__impl_to_schema_legacy_query!($ty);
    };
    ($ty:ty, Path) => {
        $crate::__impl_to_schema_legacy_path!($ty);
    };
    ($ty:ty, Header) => {
        $crate::__impl_to_schema_legacy_header!($ty);
    };
    ($ty:ty, Cookie) => {
        $crate::__impl_to_schema_legacy_cookie!($ty);
    };
}

/// Deprecated — use `#[into_params(parameter_in = Query)]` + [`impl_to_schema!`].
#[macro_export]
#[deprecated(
    note = "use #[into_params(parameter_in = Query)] on the struct and impl_to_schema!(T)"
)]
macro_rules! impl_to_schema_query {
    ($ty:ty) => {
        $crate::__impl_to_schema_legacy_query!($ty);
    };
}

/// Deprecated — use `#[into_params(parameter_in = Path)]` + [`impl_to_schema!`].
#[macro_export]
#[deprecated(note = "use #[into_params(parameter_in = Path)] on the struct and impl_to_schema!(T)")]
macro_rules! impl_to_schema_path {
    ($ty:ty) => {
        $crate::__impl_to_schema_legacy_path!($ty);
    };
}

#[doc(hidden)]
#[macro_export]
#[deprecated(
    note = "use #[into_params(parameter_in = Query)] on the struct and impl_to_schema!(T)"
)]
macro_rules! __impl_to_schema_legacy_query {
    ($ty:ty) => {
        $crate::__impl_to_schema!($ty, name: None, param_in: Some($crate::utoipa::openapi::path::ParameterIn::Query));
    };
}

#[doc(hidden)]
#[macro_export]
#[deprecated(note = "use #[into_params(parameter_in = Path)] on the struct and impl_to_schema!(T)")]
macro_rules! __impl_to_schema_legacy_path {
    ($ty:ty) => {
        $crate::__impl_to_schema!($ty, name: None, param_in: Some($crate::utoipa::openapi::path::ParameterIn::Path));
    };
}

#[doc(hidden)]
#[macro_export]
#[deprecated(
    note = "use #[into_params(parameter_in = Header)] on the struct and impl_to_schema!(T)"
)]
macro_rules! __impl_to_schema_legacy_header {
    ($ty:ty) => {
        $crate::__impl_to_schema!($ty, name: None, param_in: Some($crate::utoipa::openapi::path::ParameterIn::Header));
    };
}

#[doc(hidden)]
#[macro_export]
#[deprecated(
    note = "use #[into_params(parameter_in = Cookie)] on the struct and impl_to_schema!(T)"
)]
macro_rules! __impl_to_schema_legacy_cookie {
    ($ty:ty) => {
        $crate::__impl_to_schema!($ty, name: None, param_in: Some($crate::utoipa::openapi::path::ParameterIn::Cookie));
    };
}

#[doc(hidden)]
#[macro_export]
#[deprecated(
    note = "use #[into_params(parameter_in = Query)] on the struct and impl_to_schema!(T)"
)]
macro_rules! __impl_to_schema_legacy_suffix_query {
    ($ty:ty) => {
        $crate::__impl_to_schema_legacy_query!($ty);
    };
}

#[doc(hidden)]
#[macro_export]
#[deprecated(note = "use #[into_params(parameter_in = Path)] on the struct and impl_to_schema!(T)")]
macro_rules! __impl_to_schema_legacy_suffix_path {
    ($ty:ty) => {
        $crate::__impl_to_schema_legacy_path!($ty);
    };
}

#[doc(hidden)]
#[macro_export]
#[deprecated(
    note = "use #[into_params(parameter_in = Header)] on the struct and impl_to_schema!(T)"
)]
macro_rules! __impl_to_schema_legacy_suffix_header {
    ($ty:ty) => {
        $crate::__impl_to_schema_legacy_header!($ty);
    };
}

#[doc(hidden)]
#[macro_export]
#[deprecated(
    note = "use #[into_params(parameter_in = Cookie)] on the struct and impl_to_schema!(T)"
)]
macro_rules! __impl_to_schema_legacy_suffix_cookie {
    ($ty:ty) => {
        $crate::__impl_to_schema_legacy_cookie!($ty);
    };
}

/// Re-export utoipa for use in macros
pub use utoipa;

#[doc(hidden)]
pub trait __VldNestedSchemasFallback {
    #[allow(clippy::type_complexity)]
    fn __vld_nested_schemas() -> Vec<(&'static str, fn() -> serde_json::Value)> {
        Vec::new()
    }
}

impl<T: ?Sized> __VldNestedSchemasFallback for T {}

/// Prelude module — import everything you need.
pub mod prelude {
    #[allow(deprecated)]
    pub use crate::impl_into_params;
    pub use crate::impl_to_schema;
    #[allow(deprecated)]
    pub use crate::impl_to_schema_path;
    #[allow(deprecated)]
    pub use crate::impl_to_schema_query;
    pub use crate::json_schema_to_params;
    pub use crate::json_schema_to_schema;
    pub use vld::prelude::*;
}
