//! # vld-aide — Bridge between `vld` and `aide` / `schemars`
//!
//! This crate lets you use `vld` validation schemas as the **single source of truth**
//! for both runtime validation and OpenAPI documentation generated by
//! [aide](https://docs.rs/aide) (which uses [schemars](https://docs.rs/schemars) internally).
//!
//! Instead of duplicating schema definitions with `#[derive(JsonSchema)]` **and**
//! `vld::schema!`, you define validation rules once and get `schemars` compatibility
//! for free.
//!
//! # Quick Start
//!
//! ```rust
//! use vld::prelude::*;
//! use vld_aide::impl_json_schema;
//!
//! // 1. Define your validated struct as usual
//! vld::schema! {
//!     #[derive(Debug)]
//!     pub struct User {
//!         pub name: String => vld::string().min(2).max(50),
//!         pub email: String => vld::string().email(),
//!     }
//! }
//!
//! // 2. Bridge to schemars — one line
//! impl_json_schema!(User);
//!
//! // Now `User` implements `schemars::JsonSchema` and can be used in
//! // aide routers: `aide::axum::Json<User>` etc.
//! ```
//!
//! # Converting arbitrary JSON Schema
//!
//! ```rust
//! use vld_aide::vld_to_schemars;
//!
//! let vld_schema = serde_json::json!({
//!     "type": "object",
//!     "required": ["name"],
//!     "properties": {
//!         "name": { "type": "string", "minLength": 1 }
//!     }
//! });
//!
//! let schemars_schema = vld_to_schemars(&vld_schema);
//! // Returns `schemars::Schema`
//! ```

/// Convert a `serde_json::Value` (JSON Schema) produced by `vld` into a
/// `schemars::Schema`.
///
/// `schemars::Schema` wraps a JSON value that must be either an object or a bool.
/// Since vld's `json_schema()` always returns an object, the conversion is direct.
///
/// # Example
///
/// ```rust
/// use vld_aide::vld_to_schemars;
///
/// let schema = vld_to_schemars(&serde_json::json!({"type": "string", "format": "email"}));
/// assert_eq!(schema.get("type").unwrap(), "string");
/// ```
pub fn vld_to_schemars(value: &serde_json::Value) -> schemars::Schema {
    value
        .clone()
        .try_into()
        .unwrap_or_else(|_| schemars::Schema::default())
}

/// Implement `schemars::JsonSchema` for a type that has a `json_schema()` associated
/// function (generated by `vld::schema!` with the `openapi` feature enabled, or by
/// `#[derive(Validate)]`).
///
/// This makes the type usable with `aide` for OpenAPI documentation generation.
///
/// # Usage
///
/// ```rust
/// use vld::prelude::*;
/// use vld_aide::impl_json_schema;
///
/// vld::schema! {
///     #[derive(Debug)]
///     pub struct CreateUser {
///         pub name: String => vld::string().min(2).max(100),
///         pub email: String => vld::string().email(),
///     }
/// }
///
/// impl_json_schema!(CreateUser);
///
/// // Now CreateUser implements schemars::JsonSchema and works with aide.
/// ```
///
/// You can also pass a custom schema name:
///
/// ```rust
/// # use vld::prelude::*;
/// # use vld_aide::impl_json_schema;
/// # vld::schema! {
/// #     #[derive(Debug)]
/// #     pub struct Req { pub x: String => vld::string() }
/// # }
/// impl_json_schema!(Req, "CreateUserRequest");
/// ```
#[macro_export]
macro_rules! impl_json_schema {
    ($ty:ty) => {
        impl $crate::schemars::JsonSchema for $ty {
            fn schema_name() -> ::std::borrow::Cow<'static, str> {
                ::std::borrow::Cow::Borrowed(stringify!($ty))
            }

            fn schema_id() -> ::std::borrow::Cow<'static, str> {
                ::std::borrow::Cow::Owned(concat!(module_path!(), "::", stringify!($ty)).to_owned())
            }

            fn json_schema(
                gen: &mut $crate::schemars::SchemaGenerator,
            ) -> $crate::schemars::Schema {
                #[allow(unused_imports)]
                use $crate::__VldNestedSchemasFallback as _;
                for (name, schema_fn) in <$ty>::__vld_nested_schemas() {
                    gen.definitions_mut()
                        .entry(name.to_string())
                        .or_insert_with(|| schema_fn());
                }
                $crate::vld_to_schemars(&<$ty>::json_schema())
            }
        }
    };
    ($ty:ty, $name:expr) => {
        impl $crate::schemars::JsonSchema for $ty {
            fn schema_name() -> ::std::borrow::Cow<'static, str> {
                ::std::borrow::Cow::Borrowed($name)
            }

            fn schema_id() -> ::std::borrow::Cow<'static, str> {
                ::std::borrow::Cow::Owned(format!("{}::{}", module_path!(), $name))
            }

            fn json_schema(
                gen: &mut $crate::schemars::SchemaGenerator,
            ) -> $crate::schemars::Schema {
                #[allow(unused_imports)]
                use $crate::__VldNestedSchemasFallback as _;
                for (name, schema_fn) in <$ty>::__vld_nested_schemas() {
                    gen.definitions_mut()
                        .entry(name.to_string())
                        .or_insert_with(|| schema_fn());
                }
                $crate::vld_to_schemars(&<$ty>::json_schema())
            }
        }
    };
}

/// Re-export schemars for use in macros.
pub use schemars;

#[doc(hidden)]
pub trait __VldNestedSchemasFallback {
    #[allow(clippy::type_complexity)]
    fn __vld_nested_schemas() -> Vec<(&'static str, fn() -> serde_json::Value)> {
        Vec::new()
    }
}

impl<T: ?Sized> __VldNestedSchemasFallback for T {}

/// Prelude module — import everything you need.
pub mod prelude {
    pub use crate::impl_json_schema;
    pub use crate::vld_to_schemars;
    pub use vld::prelude::*;
}
