use serde::{Deserialize, Serialize};
use tonic::Request;

// Simulated protobuf message (in real projects, generated by prost)
#[derive(Debug, Clone, Serialize, Deserialize)]
struct CreateUserRequest {
    name: String,
    email: String,
    age: i32,
}

// Attach vld validation rules
vld_tonic::impl_validate!(CreateUserRequest {
    name  => vld::string().min(2).max(50),
    email => vld::string().email(),
    age   => vld::number().int().min(0).max(150),
});

// Metadata schema
vld::schema! {
    #[derive(Debug, Clone)]
    struct AuthMetadata {
        authorization: String => vld::string().starts_with("Bearer "),
    }
}

fn main() {
    println!("=== Message validation (impl_validate!) ===\n");

    // Valid message
    let req = Request::new(CreateUserRequest {
        name: "Alice".into(),
        email: "alice@example.com".into(),
        age: 30,
    });

    match vld_tonic::validate(req) {
        Ok(msg) => println!("Valid: {:?}", msg),
        Err(status) => println!("Error: {}", status.message()),
    }

    // Invalid message
    let req = Request::new(CreateUserRequest {
        name: "A".into(),
        email: "bad".into(),
        age: -5,
    });

    match vld_tonic::validate(req) {
        Ok(msg) => println!("Valid: {:?}", msg),
        Err(status) => println!("Error: {}", status.message()),
    }

    // Direct validation via inherent methods
    let msg = CreateUserRequest {
        name: "Bob".into(),
        email: "bob@test.com".into(),
        age: 25,
    };
    println!("\nis_valid: {}", msg.is_valid());

    println!("\n=== Schema-based validation (validate_with) ===\n");

    vld::schema! {
        #[derive(Debug)]
        struct UserSchema {
            name: String  => vld::string().min(2),
            email: String => vld::string().email(),
        }
    }

    #[derive(Serialize)]
    struct SimpleMsg {
        name: String,
        email: String,
    }

    let req = Request::new(SimpleMsg {
        name: "Charlie".into(),
        email: "c@d.com".into(),
    });
    match vld_tonic::validate_with::<UserSchema, _>(req) {
        Ok(_) => println!("Schema validation passed"),
        Err(status) => println!("Error: {}", status.message()),
    }

    println!("\n=== Metadata validation ===\n");

    let mut req: Request<()> = Request::new(());
    req.metadata_mut()
        .insert("authorization", "Bearer my-token".parse().unwrap());

    match vld_tonic::validate_metadata::<AuthMetadata, _>(&req) {
        Ok(auth) => println!("Auth: {:?}", auth),
        Err(status) => println!("Error: {}", status.message()),
    }

    // Missing authorization
    let req: Request<()> = Request::new(());
    match vld_tonic::validate_metadata::<AuthMetadata, _>(&req) {
        Ok(auth) => println!("Auth: {:?}", auth),
        Err(status) => println!("Metadata error (expected): {}", status.code()),
    }

    println!("\n=== Interceptor pattern ===\n");

    let mut req: Request<()> = Request::new(());
    req.metadata_mut()
        .insert("authorization", "Bearer intercepted".parse().unwrap());

    match vld_tonic::metadata_interceptor::<AuthMetadata>(req) {
        Ok(req) => {
            let auth = req.extensions().get::<AuthMetadata>().unwrap();
            println!("Interceptor stored: {:?}", auth);
        }
        Err(status) => println!("Interceptor rejected: {}", status.message()),
    }
}
