//! Dictionaries of realistic fake data.

// ═══════════════════════════════════════════════════════════════════════════
//  People
// ═══════════════════════════════════════════════════════════════════════════

pub const FIRST_NAMES: &[&str] = &[
    "James",
    "Mary",
    "Robert",
    "Patricia",
    "John",
    "Jennifer",
    "Michael",
    "Linda",
    "David",
    "Elizabeth",
    "William",
    "Barbara",
    "Richard",
    "Susan",
    "Joseph",
    "Jessica",
    "Thomas",
    "Sarah",
    "Charles",
    "Karen",
    "Christopher",
    "Lisa",
    "Daniel",
    "Nancy",
    "Matthew",
    "Betty",
    "Anthony",
    "Margaret",
    "Mark",
    "Sandra",
    "Donald",
    "Ashley",
    "Steven",
    "Dorothy",
    "Paul",
    "Kimberly",
    "Andrew",
    "Emily",
    "Joshua",
    "Donna",
    "Kenneth",
    "Michelle",
    "Kevin",
    "Carol",
    "Brian",
    "Amanda",
    "George",
    "Melissa",
    "Timothy",
    "Deborah",
    "Ronald",
    "Stephanie",
    "Edward",
    "Rebecca",
    "Jason",
    "Sharon",
    "Jeffrey",
    "Laura",
    "Ryan",
    "Cynthia",
    "Jacob",
    "Kathleen",
    "Gary",
    "Amy",
    "Nicholas",
    "Angela",
    "Eric",
    "Shirley",
    "Jonathan",
    "Anna",
    "Stephen",
    "Brenda",
    "Larry",
    "Pamela",
    "Justin",
    "Emma",
    "Scott",
    "Nicole",
    "Brandon",
    "Helen",
    "Benjamin",
    "Samantha",
    "Samuel",
    "Katherine",
    "Raymond",
    "Christine",
    "Gregory",
    "Debra",
    "Frank",
    "Rachel",
    "Alexander",
    "Carolyn",
    "Patrick",
    "Janet",
    "Jack",
    "Catherine",
    "Dennis",
    "Maria",
    "Jerry",
    "Heather",
    "Tyler",
    "Diane",
    "Aaron",
    "Ruth",
    "Jose",
    "Julie",
    "Adam",
    "Olivia",
    "Nathan",
    "Joyce",
    "Henry",
    "Virginia",
    "Zachary",
    "Victoria",
    "Douglas",
    "Kelly",
    "Peter",
    "Lauren",
    "Kyle",
    "Christina",
    "Noah",
    "Joan",
    "Ethan",
    "Evelyn",
    "Jeremy",
    "Judith",
    "Walter",
    "Megan",
    "Christian",
    "Andrea",
    "Keith",
    "Cheryl",
    "Roger",
    "Hannah",
    "Terry",
    "Jacqueline",
    "Austin",
    "Martha",
    "Sean",
    "Gloria",
    "Gerald",
    "Teresa",
    "Carl",
    "Ann",
    "Dylan",
    "Sara",
    "Harold",
    "Madison",
    "Jordan",
    "Frances",
    "Jesse",
    "Kathryn",
    "Bryan",
    "Janice",
    "Lawrence",
    "Jean",
    "Arthur",
    "Abigail",
    "Gabriel",
    "Alice",
    "Bruce",
    "Judy",
    "Albert",
    "Sophia",
    "Willie",
    "Grace",
    "Alan",
    "Denise",
    "Eugene",
    "Amber",
    "Logan",
    "Doris",
    "Wayne",
    "Marilyn",
    "Elijah",
    "Danielle",
    "Randy",
    "Beverly",
    "Roy",
    "Isabella",
    "Vincent",
    "Theresa",
    "Ralph",
    "Diana",
    "Russell",
    "Natalie",
    "Bobby",
    "Brittany",
    "Mason",
    "Charlotte",
    "Philip",
    "Marie",
    "Harry",
    "Kayla",
    "Liam",
    "Alexis",
    "Oliver",
    "Lori",
];

pub const LAST_NAMES: &[&str] = &[
    "Smith",
    "Johnson",
    "Williams",
    "Brown",
    "Jones",
    "Garcia",
    "Miller",
    "Davis",
    "Rodriguez",
    "Martinez",
    "Hernandez",
    "Lopez",
    "Gonzalez",
    "Wilson",
    "Anderson",
    "Thomas",
    "Taylor",
    "Moore",
    "Jackson",
    "Martin",
    "Lee",
    "Perez",
    "Thompson",
    "White",
    "Harris",
    "Sanchez",
    "Clark",
    "Ramirez",
    "Lewis",
    "Robinson",
    "Walker",
    "Young",
    "Allen",
    "King",
    "Wright",
    "Scott",
    "Torres",
    "Nguyen",
    "Hill",
    "Flores",
    "Green",
    "Adams",
    "Nelson",
    "Baker",
    "Hall",
    "Rivera",
    "Campbell",
    "Mitchell",
    "Carter",
    "Roberts",
    "Gomez",
    "Phillips",
    "Evans",
    "Turner",
    "Diaz",
    "Parker",
    "Cruz",
    "Edwards",
    "Collins",
    "Reyes",
    "Stewart",
    "Morris",
    "Morales",
    "Murphy",
    "Cook",
    "Rogers",
    "Gutierrez",
    "Ortiz",
    "Morgan",
    "Cooper",
    "Peterson",
    "Bailey",
    "Reed",
    "Kelly",
    "Howard",
    "Ramos",
    "Kim",
    "Cox",
    "Ward",
    "Richardson",
    "Watson",
    "Brooks",
    "Chavez",
    "Wood",
    "James",
    "Bennett",
    "Gray",
    "Mendoza",
    "Ruiz",
    "Hughes",
    "Price",
    "Alvarez",
    "Castillo",
    "Sanders",
    "Patel",
    "Myers",
    "Long",
    "Ross",
    "Foster",
    "Jimenez",
    "Powell",
    "Jenkins",
    "Perry",
    "Russell",
    "Sullivan",
    "Bell",
    "Coleman",
    "Butler",
    "Henderson",
    "Barnes",
    "Gonzales",
    "Fisher",
    "Vasquez",
    "Simmons",
    "Griffin",
    "Hart",
    "Walsh",
    "West",
    "Cole",
    "Hunt",
    "Dunn",
    "Ford",
    "Marshall",
    "Harrison",
    "Hicks",
    "Dean",
    "Wagner",
];

// ═══════════════════════════════════════════════════════════════════════════
//  Geography
// ═══════════════════════════════════════════════════════════════════════════

pub const CITIES: &[&str] = &[
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Jacksonville",
    "Fort Worth",
    "Columbus",
    "Charlotte",
    "Indianapolis",
    "San Francisco",
    "Seattle",
    "Denver",
    "Nashville",
    "Oklahoma City",
    "Portland",
    "Las Vegas",
    "Memphis",
    "Louisville",
    "Baltimore",
    "Milwaukee",
    "Albuquerque",
    "Tucson",
    "Fresno",
    "Sacramento",
    "Mesa",
    "Kansas City",
    "Atlanta",
    "Omaha",
    "Colorado Springs",
    "Raleigh",
    "Virginia Beach",
    "Long Beach",
    "Miami",
    "Oakland",
    "Minneapolis",
    "Tampa",
    "Tulsa",
    "Arlington",
    "New Orleans",
    "London",
    "Paris",
    "Berlin",
    "Madrid",
    "Rome",
    "Amsterdam",
    "Vienna",
    "Prague",
    "Brussels",
    "Stockholm",
    "Oslo",
    "Helsinki",
    "Dublin",
    "Lisbon",
    "Warsaw",
    "Budapest",
    "Copenhagen",
    "Athens",
    "Zurich",
    "Munich",
    "Barcelona",
    "Tokyo",
    "Seoul",
    "Beijing",
    "Shanghai",
    "Mumbai",
    "Delhi",
    "Bangkok",
    "Singapore",
    "Sydney",
    "Melbourne",
    "Toronto",
    "Vancouver",
    "Montreal",
    "São Paulo",
    "Buenos Aires",
    "Mexico City",
    "Lima",
    "Bogotá",
    "Santiago",
    "Cape Town",
    "Cairo",
    "Nairobi",
    "Lagos",
    "Casablanca",
    "Dubai",
    "Istanbul",
];

pub const COUNTRIES: &[&str] = &[
    "United States",
    "Canada",
    "United Kingdom",
    "Germany",
    "France",
    "Italy",
    "Spain",
    "Netherlands",
    "Belgium",
    "Switzerland",
    "Austria",
    "Sweden",
    "Norway",
    "Denmark",
    "Finland",
    "Ireland",
    "Portugal",
    "Poland",
    "Czech Republic",
    "Hungary",
    "Romania",
    "Greece",
    "Turkey",
    "Russia",
    "Ukraine",
    "Japan",
    "South Korea",
    "China",
    "India",
    "Australia",
    "New Zealand",
    "Brazil",
    "Argentina",
    "Mexico",
    "Colombia",
    "Chile",
    "Peru",
    "South Africa",
    "Egypt",
    "Nigeria",
    "Kenya",
    "Morocco",
    "United Arab Emirates",
    "Singapore",
    "Thailand",
    "Vietnam",
    "Indonesia",
    "Philippines",
    "Malaysia",
    "Israel",
];

pub const STATES: &[&str] = &[
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
];

pub const STREET_NAMES: &[&str] = &[
    "Main",
    "Oak",
    "Pine",
    "Maple",
    "Cedar",
    "Elm",
    "Washington",
    "Park",
    "Walnut",
    "Sunset",
    "Highland",
    "Lake",
    "Hill",
    "Forest",
    "River",
    "Spring",
    "Valley",
    "Church",
    "Market",
    "Union",
    "Liberty",
    "Madison",
    "Franklin",
    "Lincoln",
    "Jefferson",
    "Adams",
    "Jackson",
    "Wilson",
    "Broadway",
    "Center",
    "Front",
    "Mill",
    "Academy",
    "School",
    "Court",
    "Prospect",
    "Grove",
    "Meadow",
    "Ridge",
    "Willow",
    "Birch",
    "Hickory",
    "Lakeview",
    "Fairview",
    "Orchard",
    "Summit",
    "Harbor",
    "Chestnut",
];

pub const STREET_SUFFIXES: &[&str] = &[
    "Street",
    "Avenue",
    "Boulevard",
    "Drive",
    "Lane",
    "Road",
    "Court",
    "Place",
    "Way",
    "Circle",
    "Trail",
    "Parkway",
    "Terrace",
    "Loop",
    "Alley",
    "Row",
    "Path",
    "Square",
    "Highway",
    "Crossing",
];

// ═══════════════════════════════════════════════════════════════════════════
//  Company / Job
// ═══════════════════════════════════════════════════════════════════════════

pub const COMPANIES: &[&str] = &[
    "Acme Corp",
    "Globex Corporation",
    "Soylent Corp",
    "Initech",
    "Hooli",
    "Pied Piper",
    "Stark Industries",
    "Wayne Enterprises",
    "Oscorp",
    "Umbrella Corp",
    "Cyberdyne Systems",
    "Weyland-Yutani",
    "InGen",
    "Massive Dynamic",
    "TechNova",
    "CloudSync",
    "DataForge",
    "NexGen Solutions",
    "BluePeak Systems",
    "GreenField Analytics",
    "SilverLine Software",
    "IronBridge Technologies",
    "Quantum Dynamics",
    "Apex Innovations",
    "Synergy Partners",
    "Horizon Labs",
    "Pinnacle Consulting",
    "Vertex Group",
    "Atlas Digital",
    "Cobalt Networks",
    "Sapphire Systems",
    "Onyx Solutions",
    "Prism Technologies",
    "Fusion Enterprises",
    "Catalyst Corp",
    "Momentum Inc",
    "Zenith Global",
    "Vanguard Tech",
    "Nova Industries",
    "Sterling & Associates",
    "Summit Digital",
];

pub const DEPARTMENTS: &[&str] = &[
    "Engineering",
    "Marketing",
    "Sales",
    "Human Resources",
    "Finance",
    "Operations",
    "Legal",
    "Customer Support",
    "Research & Development",
    "Product Management",
    "Quality Assurance",
    "Design",
    "IT",
    "Security",
    "Business Development",
    "Data Science",
    "DevOps",
    "Analytics",
    "Public Relations",
    "Compliance",
    "Logistics",
    "Procurement",
];

pub const JOB_TITLES: &[&str] = &[
    "Software Engineer",
    "Senior Developer",
    "Product Manager",
    "Data Analyst",
    "UX Designer",
    "DevOps Engineer",
    "QA Engineer",
    "Tech Lead",
    "Engineering Manager",
    "CTO",
    "VP of Engineering",
    "Full Stack Developer",
    "Frontend Developer",
    "Backend Developer",
    "Cloud Architect",
    "SRE",
    "Data Scientist",
    "Machine Learning Engineer",
    "Security Analyst",
    "Project Manager",
    "Scrum Master",
    "Business Analyst",
    "Marketing Manager",
    "Sales Representative",
    "Account Executive",
    "Customer Success Manager",
    "HR Specialist",
    "Financial Analyst",
    "Operations Manager",
    "Legal Counsel",
    "Content Writer",
    "Graphic Designer",
    "Systems Administrator",
    "Database Administrator",
    "Network Engineer",
    "Mobile Developer",
    "Research Scientist",
    "Solutions Architect",
    "Technical Writer",
];

// ═══════════════════════════════════════════════════════════════════════════
//  Products / Commerce
// ═══════════════════════════════════════════════════════════════════════════

pub const ADJECTIVES: &[&str] = &[
    "Premium",
    "Deluxe",
    "Ultimate",
    "Professional",
    "Classic",
    "Modern",
    "Elegant",
    "Compact",
    "Portable",
    "Advanced",
    "Smart",
    "Wireless",
    "Organic",
    "Natural",
    "Handcrafted",
    "Vintage",
    "Rustic",
    "Luxury",
    "Essential",
    "Elite",
    "Eco-Friendly",
    "Heavy-Duty",
    "Lightweight",
    "High-Performance",
    "Ergonomic",
    "Slim",
    "Ultra",
    "Custom",
    "Artisan",
    "Innovative",
    "Durable",
    "Sleek",
    "Powerful",
    "Refined",
    "Exclusive",
];

pub const PRODUCT_NOUNS: &[&str] = &[
    "Laptop",
    "Keyboard",
    "Mouse",
    "Monitor",
    "Headphones",
    "Speaker",
    "Camera",
    "Phone",
    "Tablet",
    "Watch",
    "Charger",
    "Cable",
    "Adapter",
    "Backpack",
    "Wallet",
    "Notebook",
    "Pen",
    "Mug",
    "Bottle",
    "Lamp",
    "Chair",
    "Desk",
    "Shelf",
    "Organizer",
    "Mat",
    "Stand",
    "Hub",
    "Drive",
    "Router",
    "Microphone",
    "Webcam",
    "Controller",
    "Console",
    "Printer",
    "Scanner",
    "Projector",
    "Docking Station",
    "Power Bank",
];

pub const CATEGORIES: &[&str] = &[
    "Electronics",
    "Books",
    "Clothing",
    "Home & Garden",
    "Sports",
    "Toys",
    "Health & Beauty",
    "Automotive",
    "Food & Beverages",
    "Music",
    "Software",
    "Games",
    "Office Supplies",
    "Pet Supplies",
    "Art",
    "Travel",
    "Education",
    "Finance",
    "Entertainment",
    "Photography",
    "Fitness",
    "Cooking",
    "Science",
    "Technology",
    "Fashion",
    "Outdoors",
];

pub const TAGS: &[&str] = &[
    "new",
    "sale",
    "popular",
    "trending",
    "featured",
    "bestseller",
    "limited",
    "exclusive",
    "premium",
    "free-shipping",
    "eco-friendly",
    "handmade",
    "organic",
    "vintage",
    "clearance",
    "bundle",
    "refurbished",
    "imported",
    "local",
    "seasonal",
    "essential",
    "gift-idea",
    "top-rated",
    "editor-pick",
    "staff-favorite",
    "award-winning",
    "innovative",
];

// ═══════════════════════════════════════════════════════════════════════════
//  Places / Geo
// ═══════════════════════════════════════════════════════════════════════════

pub const PLACE_CATEGORIES: &[&str] = &[
    "Restaurant",
    "Café",
    "Bar",
    "Hotel",
    "Museum",
    "Park",
    "Library",
    "Theater",
    "Cinema",
    "Gym",
    "Hospital",
    "Pharmacy",
    "School",
    "University",
    "Airport",
    "Station",
    "Mall",
    "Market",
    "Gallery",
    "Stadium",
    "Arena",
    "Temple",
    "Church",
    "Mosque",
    "Synagogue",
    "Beach",
    "Mountain",
    "Lake",
    "Bridge",
    "Monument",
    "Memorial",
    "Zoo",
    "Aquarium",
    "Botanical Garden",
    "Observatory",
    "Spa",
];

pub const PLACE_NOUNS: &[&str] = &[
    "Plaza",
    "Tower",
    "Garden",
    "Square",
    "Court",
    "Lodge",
    "Manor",
    "Palace",
    "Residence",
    "Terrace",
    "Haven",
    "Retreat",
    "Oasis",
    "Pavilion",
    "Promenade",
    "Atrium",
    "Arcade",
    "Commons",
    "Quarter",
    "District",
    "Hub",
    "Center",
    "Point",
    "Crossing",
    "Landing",
    "Wharf",
    "Pier",
    "Dock",
    "Cove",
    "Bay",
    "Ridge",
    "Summit",
    "Valley",
    "Meadow",
    "Grove",
    "Bluff",
    "Cliff",
    "Canyon",
];

pub const INDUSTRIES: &[&str] = &[
    "Technology",
    "Healthcare",
    "Finance",
    "Education",
    "Manufacturing",
    "Retail",
    "Real Estate",
    "Transportation",
    "Energy",
    "Telecommunications",
    "Media & Entertainment",
    "Agriculture",
    "Construction",
    "Hospitality",
    "Aerospace & Defense",
    "Automotive",
    "Pharmaceuticals",
    "Insurance",
    "Consulting",
    "Legal Services",
    "Food & Beverage",
    "Mining",
    "Logistics",
    "E-commerce",
    "Biotechnology",
    "Cybersecurity",
    "Renewable Energy",
    "Artificial Intelligence",
    "FinTech",
    "EdTech",
];

// ═══════════════════════════════════════════════════════════════════════════
//  Internet / Tech
// ═══════════════════════════════════════════════════════════════════════════

pub const EMAIL_DOMAINS: &[&str] = &[
    "gmail.com",
    "yahoo.com",
    "outlook.com",
    "hotmail.com",
    "protonmail.com",
    "icloud.com",
    "mail.com",
    "zoho.com",
    "fastmail.com",
    "tutanota.com",
    "example.com",
    "test.org",
    "demo.net",
    "company.io",
    "work.co",
];

pub const TLDS: &[&str] = &[
    "com", "org", "net", "io", "co", "dev", "app", "ai", "tech", "info", "biz", "me", "us", "uk",
    "de", "fr", "jp", "ru", "xyz", "online", "site", "store", "blog", "cloud",
];

pub const MIME_TYPES: &[&str] = &[
    "application/json",
    "application/xml",
    "application/pdf",
    "application/zip",
    "application/octet-stream",
    "text/html",
    "text/plain",
    "text/css",
    "text/csv",
    "image/png",
    "image/jpeg",
    "image/gif",
    "image/svg+xml",
    "image/webp",
    "audio/mpeg",
    "audio/wav",
    "audio/ogg",
    "video/mp4",
    "video/webm",
    "multipart/form-data",
];

pub const FILE_EXTENSIONS: &[&str] = &[
    "txt", "pdf", "doc", "docx", "xls", "xlsx", "ppt", "pptx", "jpg", "jpeg", "png", "gif", "svg",
    "webp", "bmp", "mp3", "wav", "ogg", "mp4", "webm", "avi", "mkv", "zip", "tar", "gz", "rar",
    "7z", "json", "xml", "csv", "yaml", "toml", "html", "css", "js", "ts", "rs", "py", "go",
    "java", "md", "log", "sql", "sh", "bat",
];

pub const COLORS: &[&str] = &[
    "Red",
    "Blue",
    "Green",
    "Yellow",
    "Orange",
    "Purple",
    "Pink",
    "Brown",
    "Black",
    "White",
    "Gray",
    "Silver",
    "Gold",
    "Navy",
    "Teal",
    "Coral",
    "Maroon",
    "Olive",
    "Cyan",
    "Magenta",
    "Crimson",
    "Indigo",
    "Ivory",
    "Lavender",
    "Salmon",
    "Turquoise",
    "Violet",
    "Beige",
    "Khaki",
    "Mint",
    "Peach",
    "Plum",
    "Slate",
    "Charcoal",
    "Azure",
    "Burgundy",
    "Emerald",
    "Scarlet",
    "Sapphire",
];

pub const CURRENCIES: &[&str] = &[
    "USD", "EUR", "GBP", "JPY", "CNY", "KRW", "INR", "CAD", "AUD", "CHF", "SEK", "NOK", "DKK",
    "RUB", "BRL", "MXN", "ZAR", "SGD", "HKD", "NZD", "TRY", "PLN", "THB", "IDR", "PHP", "MYR",
    "AED",
];

pub const LOCALES: &[&str] = &[
    "en-US", "en-GB", "en-AU", "en-CA", "fr-FR", "de-DE", "es-ES", "it-IT", "pt-BR", "ja-JP",
    "ko-KR", "zh-CN", "zh-TW", "ru-RU", "nl-NL", "sv-SE", "no-NO", "da-DK", "fi-FI", "pl-PL",
    "cs-CZ", "hu-HU", "ro-RO", "el-GR", "tr-TR", "ar-SA", "he-IL", "th-TH", "vi-VN", "id-ID",
    "ms-MY", "uk-UA", "bg-BG", "hr-HR", "sk-SK",
];

pub const TIMEZONES: &[&str] = &[
    "UTC",
    "America/New_York",
    "America/Chicago",
    "America/Denver",
    "America/Los_Angeles",
    "America/Toronto",
    "America/Vancouver",
    "America/Sao_Paulo",
    "America/Argentina/Buenos_Aires",
    "America/Mexico_City",
    "Europe/London",
    "Europe/Paris",
    "Europe/Berlin",
    "Europe/Madrid",
    "Europe/Rome",
    "Europe/Amsterdam",
    "Europe/Moscow",
    "Europe/Istanbul",
    "Asia/Tokyo",
    "Asia/Seoul",
    "Asia/Shanghai",
    "Asia/Hong_Kong",
    "Asia/Singapore",
    "Asia/Kolkata",
    "Asia/Dubai",
    "Asia/Bangkok",
    "Australia/Sydney",
    "Australia/Melbourne",
    "Pacific/Auckland",
    "Africa/Cairo",
    "Africa/Johannesburg",
    "Africa/Lagos",
];

// ═══════════════════════════════════════════════════════════════════════════
//  Emoji
// ═══════════════════════════════════════════════════════════════════════════

pub const EMOJIS: &[&str] = &[
    "\u{1F600}",
    "\u{1F603}",
    "\u{1F604}",
    "\u{1F601}",
    "\u{1F606}",
    "\u{1F605}",
    "\u{1F602}",
    "\u{1F923}",
    "\u{1F60A}",
    "\u{1F607}",
    "\u{1F60D}",
    "\u{1F929}",
    "\u{1F618}",
    "\u{1F617}",
    "\u{1F619}",
    "\u{1F60B}",
    "\u{1F61C}",
    "\u{1F61D}",
    "\u{1F911}",
    "\u{1F917}",
    "\u{1F914}",
    "\u{1F910}",
    "\u{1F928}",
    "\u{1F644}",
    "\u{1F612}",
    "\u{1F60E}",
    "\u{1F913}",
    "\u{1F9D0}",
    "\u{1F615}",
    "\u{1F641}",
    "\u{2764}",
    "\u{1F494}",
    "\u{1F495}",
    "\u{1F496}",
    "\u{1F497}",
    "\u{1F44D}",
    "\u{1F44E}",
    "\u{1F44F}",
    "\u{1F64C}",
    "\u{1F91D}",
    "\u{1F4AA}",
    "\u{270C}",
    "\u{1F918}",
    "\u{1F919}",
    "\u{1F91E}",
    "\u{1F680}",
    "\u{2728}",
    "\u{1F525}",
    "\u{1F31F}",
    "\u{1F389}",
    "\u{1F38A}",
    "\u{1F3C6}",
    "\u{1F3AF}",
    "\u{1F4A1}",
    "\u{1F4A5}",
    "\u{1F308}",
    "\u{2600}",
    "\u{1F326}",
    "\u{2744}",
    "\u{1F340}",
];

// ═══════════════════════════════════════════════════════════════════════════
//  Words (for readable text generation)
// ═══════════════════════════════════════════════════════════════════════════

pub const WORDS: &[&str] = &[
    "alpha", "beta", "gamma", "delta", "epsilon", "zeta", "theta", "kappa", "lambda", "sigma",
    "omega", "phoenix", "atlas", "nova", "prism", "nexus", "apex", "zenith", "horizon", "summit",
    "vertex", "matrix", "vector", "cipher", "quantum", "nebula", "cosmos", "orbital", "pulsar",
    "fusion", "helix", "crystal", "titan", "vortex", "echo", "pulse", "spark", "blaze", "frost",
    "storm", "swift", "brave", "keen", "bold", "bright", "calm", "clear", "crisp", "dawn", "dusk",
    "glow", "haze", "light", "mist", "rain", "shade", "shine", "wave", "wind", "bloom", "coral",
    "ember", "fern", "grove", "ivory", "jade", "lunar", "maple", "north", "oak", "pearl", "quartz",
    "river", "sage", "stone", "terra", "unity", "vale", "willow", "azure", "cedar", "drift",
    "flint",
];

/// Words more suited for lorem-ipsum style sentences.
pub const LOREM_WORDS: &[&str] = &[
    "the",
    "a",
    "an",
    "this",
    "that",
    "these",
    "those",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "being",
    "have",
    "has",
    "had",
    "do",
    "does",
    "did",
    "will",
    "shall",
    "would",
    "should",
    "may",
    "might",
    "can",
    "could",
    "and",
    "but",
    "or",
    "nor",
    "for",
    "yet",
    "so",
    "in",
    "on",
    "at",
    "to",
    "from",
    "by",
    "with",
    "about",
    "of",
    "between",
    "through",
    "during",
    "before",
    "after",
    "system",
    "data",
    "process",
    "user",
    "application",
    "interface",
    "module",
    "component",
    "service",
    "function",
    "method",
    "class",
    "object",
    "value",
    "type",
    "operation",
    "action",
    "event",
    "state",
    "result",
    "request",
    "response",
    "message",
    "error",
    "status",
    "configuration",
    "parameter",
    "option",
    "setting",
    "property",
    "input",
    "output",
    "source",
    "target",
    "context",
    "important",
    "primary",
    "secondary",
    "global",
    "local",
    "current",
    "previous",
    "next",
    "first",
    "last",
    "new",
    "old",
    "active",
    "inactive",
    "valid",
    "invalid",
    "default",
    "custom",
    "standard",
    "specific",
    "general",
    "provides",
    "enables",
    "supports",
    "handles",
    "manages",
    "creates",
    "updates",
    "removes",
    "validates",
    "processes",
    "returns",
    "contains",
    "represents",
    "defines",
    "implements",
    "efficient",
    "reliable",
    "scalable",
    "flexible",
    "robust",
    "simple",
    "complex",
    "dynamic",
    "static",
    "structured",
    "performance",
    "security",
    "quality",
    "functionality",
    "capability",
    "resource",
    "element",
    "instance",
    "reference",
    "collection",
];
